from __future__ import annotations

# Curated list of common resume / JD skills.
# Keep it lowercase; matching is done case-insensitively.
SKILLS: list[str] = [
    # Programming
    "python",
    "java",
    "c",
    "c++",
    "c#",
    "javascript",
    "typescript",
    "go",
    "golang",
    "rust",
    "php",
    "ruby",
    "kotlin",
    "swift",
    "scala",
    "r",
    "matlab",
    "sql",
    "nosql",
    "bash",
    "powershell",
    # Web
    "html",
    "css",
    "react",
    "angular",
    "vue",
    "node.js",
    "nodejs",
    "express",
    "flask",
    "django",
    "fastapi",
    "rest",
    "graphql",
    # Data / ML
    "machine learning",
    "deep learning",
    "nlp",
    "natural language processing",
    "data science",
    "data analysis",
    "statistics",
    "pandas",
    "numpy",
    "scikit-learn",
    "sklearn",
    "tensorflow",
    "pytorch",
    "keras",
    "opencv",
    "xgboost",
    "lightgbm",
    # Cloud / DevOps
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "ci/cd",
    "github actions",
    "jenkins",
    "linux",
    # Databases
    "postgresql",
    "mysql",
    "sqlite",
    "mongodb",
    "redis",
    "elasticsearch",
    # Tools
    "git",
    "jira",
    "tableau",
    "power bi",
    "excel",
    # Concepts
    "oop",
    "data structures",
    "algorithms",
    "system design",
    "microservices",
    "unit testing",
    "pytest",
]
